### ISSUE TITLE
Adding puppeeter cluster to this project

### ISSUE THREAD

**Issue by Festouille** [silvestrodecaro/microsoft-account-creator#12]
Hello again, I saw in ur pinned repos that u created a repo that helps create multiple accounts, with one fingerprint, why not implementing it in this project ? 

I tried to create a code with python (the only language I know), and I had an issue with the CAPTCHAs, telling me to handle 20 CAPTCHAs, instead of 2/3/4/5 when I do it manually, I tried changing user agent, IP, Python webbrowser, still got 20 CAPTCHAs, how do you escape this detection in your code ?

**Comment by silvestrodecaro** [comment]
Hi, I have not implemented puppeteer cluster to my project because running multiple executions on microsoft can give problems of bad captcha or bad accounts. The solution would be to use few instances with proxy but I want to make it mandatory for the user.

Regarding the captcha, the main work is done by the IP and the fingerprint (which in this case is totally human-likely generated by the library)

**Comment by Festouille** [comment]
[like]  Mohamed akram CHERKAOUI reacted to your message:
________________________________
