### ISSUE TITLE
Unable to set viewport size

### ISSUE THREAD

**Issue by badcaf3** [silvestrodecaro/microsoft-account-creator#8]
how to solve captcha when it looks like this???
![image](https://github.com/user-attachments/assets/6954aacb-fe94-4708-ad88-f80f7c1c3278)

**Comment by silvestrodecaro** [comment]
The error message "Unable to set viewport size" is not critical. It occurs due to the "puppeteer-with-fingerprints" library attempting to set the browser's viewport size but failing to do so. This issue doesn't affect the overall functionality and can be safely ignored.

Regarding the captcha, can you give me more examples?

**Comment by silvestrodecaro** [comment]
what is your screen resolution?

**Comment by silvestrodecaro** [comment]
Check out the latest update, I just added a check for the browser resolution, if it’s bigger than the user's screen resolution, the process will restart :)
